/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package url.shortener.app;

import url.shortener.list.LinkedList;

import static url.shortener.utilities.StringUtils.join;
import static url.shortener.utilities.StringUtils.split;
import static url.shortener.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
